# Generated by Django 3.2.6 on 2021-09-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Primanry_Issue',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Secondary_Issue',
            new_name='Case_Analysis',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='description',
            new_name='Presenting_Compliance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Dependant',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='description_secondary',
        ),
        migrations.AddField(
            model_name='patient',
            name='Clinical_Conditions',
            field=models.CharField(blank=True, choices=[('DM', 'DM'), ('HTN', 'HTN'), ('HIPOTHYROIDISM', 'HIPOTHYROIDISM'), ('HYPERLIPIDIMIA', 'HYPERLIPIDIMIA'), ('HEARTCONDITIONS', 'HEARTCONDITIONS')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Email_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Family_History',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Lifespace_Investigation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Mobile_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Past_History',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Personal_History',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='alt_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Not willing to disclose', 'Not willing')], max_length=100, null=True),
        ),
    ]
